# docker-compose.yml
version: '3.8'

services: 
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_PATH}:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
